### ISSUE TITLE
Bad #if in GCC ARMCM0 port 

### ISSUE THREAD

**Issue by dc42** [FreeRTOS/FreeRTOS-Kernel#1]
File FreeRTOS-Kernel/portable/GCC/ARM_CM0/port.c contains two instances of the following #if directive:

`#if !defined (__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)`

This makes no sense at all, because if __ARMCC_VERSION is not define then it should not be tested (and the subsequent test will always yield false). Also it is not MISRA-compliant, and it rightly causes a compiler warning if the gcc -Wundef compiler option is used. My guess is that it is supposed to read either:

`#if defined (__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)`

or

`#if !defined (__ARMCC_VERSION) || (__ARMCC_VERSION >= 6010050)`

or possibly one of these with >= replaced by <. I have replaced it by #if 0 in my copy to avoid the compiler warning.

**Comment by RichardBarry** [comment]
Thanks for pointing this out.  On first reading I agree it appears wrong.  In both cases the pre-processor checks are doing nothing more than trying to prevent compiler warnings where some compiler versions will warn with code added, and others will warn with the same code removed - it may well be that the compiler versions being checked against are old and no longer in use now anyway.  Either way I will update accordingly.
