### ISSUE TITLE
[Feature Request] The number of system calls needs to support the sizeof（uintptr_t）

### ISSUE THREAD

**Issue by snikeguo** [FreeRTOS/FreeRTOS-Kernel#1015]
**Is your feature request related to a problem? Please describe.**
I need to add a custom SystemCall instruction to execute a custom function.
However, the maximum number of system call instructions is 255.

**Describe the solution you'd like**
```
....
#define SYSTEM_CALL_User   80
#define SYSTEM_CALL_xUartSend   10001 
....
PRIVILEGED_DATA UBaseType_t uxSystemCallImplementations[ NUM_SYSTEM_CALLS ] =
{
 ...
 xUartSendImpl,
}


...
BaseType_t MPU_xUartSend(..... )
{
__asm volatile
(
    " .syntax unified                                       \n"
                " .extern MPU_xUartSendImpl                            \n"
                "                                                       \n"
                " push {r0}                                             \n"
                " mrs r0, control                                       \n"
                " tst r0, #1                                            \n"
                " pop {r0}                                              \n"
                " bne MPU_xUartSend_Unpriv                             \n"
                " MPU_xUartSend_Priv:                                  \n"
                "     b MPU_xUartSendImpl                              \n"
                " MPU_xUartSend_Unpriv                                 \n"
                "     svc %0                                            \n"
                "                                                       \n"
               pc+x : "i" ( SYSTEM_CALL_User ) : "memory" 
                pc+y : "i" ( .word SYSTEM_CALL_xUartSend   ) : "memory"  //define a word :system call id I am not familiar with assembly syntax.
);
} 
...
void vSystemCallEnter( uint32_t * pulTaskStack,
                           uint32_t ulLR,
                           uint8_t ucSystemCallNumber ) 
{
....
ulSystemCallLocation = pulTaskStack[ portOFFSET_TO_PC ];
if( ( ulSystemCallLocation >= ( uint32_t ) __syscalls_flash_start__ ) &&
            ( ulSystemCallLocation <= ( uint32_t ) __syscalls_flash_end__ ) &&
            ( pxMpuSettings->xSystemCallStackInfo.pulTaskStack == NULL ) &&
            ( uxSystemCallImplementations[ ucSystemCallNumber ] != ( UBaseType_t ) 0 ) )
{
...
 uint32_t systemCallId=*(pulTaskStack[ portOFFSET_TO_PC ]+x)；//get user system call id
if( systemCallId>=SYSTEM_CALL_User )
{
    systemCallId=*(pulTaskStack[ portOFFSET_TO_PC ]+y); 
}
.....
 ......
...
}
....
}



```

**Describe alternatives you've considered**

**How many devices will this feature impact?**
Expected volume for your product.

**What are your project timelines?**
Timeline for milestones such as design completion, testing and validation, and production.

**Additional context**

If you have the same (or similar) feature request, please upvote this issue with thumbs up 👍
and use the comments section to provide answers to the questions above.

**Comment by Skptak** [comment]
What port are you using?
The ARMv7-M and ARMv8-M architectures only support an 8 bit SVC value.
Link to the [ARMv7M Architecture doc](https://developer.arm.com/documentation/ddi0403/d/Application-Level-Architecture/Instruction-Details/Alphabetical-list-of-ARMv7-M-Thumb-instructions/SVC?lang=en)
Link to the [ARMv8M Architecture Download page](https://developer.arm.com/documentation/ddi0553/bx/?lang=en), the relevant section is C2.4.242 SVC
<img width="1014" alt="image" src="https://github.com/FreeRTOS/FreeRTOS-Kernel/assets/24749346/8b6df8ee-9873-4ea5-9e42-1784af10a090">

As this is a Hardware Limitation this request isn't a feature that FreeRTOS can support

**Comment by snikeguo** [comment]
@Skptak I have made changes to the implementation. Please refresh the page to view my ideas.

**Comment by Skptak** [comment]
Your proposed change is a larger design change, and more of a feature request. Can you open a post on the [FreeRTOS Forums](https://forums.freertos.org/) to discuss it there please?

**Comment by aggarg** [comment]
As @Skptak suggested, please open a forum issue. I am closing this one.
