### ISSUE TITLE
[Feature Request] Add CodeSonar example to the repository

### ISSUE THREAD

**Issue by markhermeling** [FreeRTOS/FreeRTOS-Kernel#1070]
CodeSonar (https://codesecure.com/our-products/codesonar/) is a popular Static Application Security Testing tool for embedded development. Much like Coverity it is able to check a codebase for MISRA violations as well as deeper seated bugs related to undefined behavior, memory issues and such.

It would be useful for FreeRTOS users to be able to out of the box use CodeSonar to check for MISRA violations. CodeSecure is also happy to provide CodeSonar to the open source project to run testing or pipelines on MISRA on merges.

This feature request will be followed up with a pull request with the appropriate artefacts. No code changes are required, it is an additional directory under 'examples'

**Comment by kar-rahul-aws** [comment]
We have linked Code Sonar here - https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/.github/third_party_tools.md.
