### ISSUE TITLE
[BUG] with configUSE_STREAM_BUFFERS==0 stream_buffer.c still requires xTaskGetCurrentTaskHandle and TASK_NOTIFICATIONS

### ISSUE THREAD

**Issue by d-otte** [FreeRTOS/FreeRTOS-Kernel#1108]
**Describe the bug**
If support for stream buffers is disabled (`#define configUSE_STREAM_BUFFERS 0`), compilation with 
`configUSE_TASK_NOTIFICATION` or `INCLUDE_xTaskGetCurrentTaskHandle` set to 0 causes an error during compilation of `stream_buffer.c`.

The [check for configUSE_TASK_NOTIFICATIONS](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fffed5e8096b1f56e97ac7ab27392a7920e6d431/stream_buffer.c#L42):
```
#if ( configUSE_TASK_NOTIFICATIONS != 1 )
    #error configUSE_TASK_NOTIFICATIONS must be set to 1 to build stream_buffer.c
#endif
```

and the [check for INCLUDE_xTaskGetCurrentTaskHandle](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fffed5e8096b1f56e97ac7ab27392a7920e6d431/stream_buffer.c#L46):
```
#if ( INCLUDE_xTaskGetCurrentTaskHandle != 1 )
    #error INCLUDE_xTaskGetCurrentTaskHandle must be set to 1 to build stream_buffer.c
#endif
```

should probably controlled by [`#if ( configUSE_STREAM_BUFFERS == 1 )`](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fffed5e8096b1f56e97ac7ab27392a7920e6d431/stream_buffer.c#L59C1-L59C38).

**To Reproduce**
build the cmake_example with the following modifications in `FreeRTOSConfig.h`:

* disable [stream buffers](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fffed5e8096b1f56e97ac7ab27392a7920e6d431/examples/template_configuration/FreeRTOSConfig.h#L265)
* disable [INCLUDE_xTaskGetCurrentTaskHandle](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/fffed5e8096b1f56e97ac7ab27392a7920e6d431/examples/template_configuration/FreeRTOSConfig.h#657)

This results in:
```
$ LC_ALL=C make
[  8%] Building C object FreeRTOS-Kernel/portable/CMakeFiles/freertos_kernel_port.dir/template/port.c.o
[  8%] Built target freertos_kernel_port
[ 16%] Building C object FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/croutine.c.o
[ 25%] Building C object FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/event_groups.c.o
[ 33%] Building C object FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/list.c.o
[ 41%] Building C object FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/queue.c.o
[ 50%] Building C object FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/stream_buffer.c.o
…/FreeRTOS-Kernel/stream_buffer.c:47:6: error: #error INCLUDE_xTaskGetCurrentTaskHandle must be set to 1 to build stream_buffer.c
   47 |     #error INCLUDE_xTaskGetCurrentTaskHandle must be set to 1 to build stream_buffer.c
      |      ^~~~~
make[2]: *** [FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/build.make:132: FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/stream_buffer.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:162: FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Expected behavior**
A successful build :)

**Additional context**
This affects at least the current main branch (fffed5e8096b1f56e97ac7ab27392a7920e6d431) and release V11.1.0 . 

A pull request is on its way :)

**Comment by kar-rahul-aws** [comment]
Hi @d-otte 
Thanks for reporting the issue. We have reviewed and merged the PR.
Thanks for your contribution .
