### ISSUE TITLE
[BUG] Uncrustify breaks CCS MSP430X data_model.h file

### ISSUE THREAD

**Issue by GaryLeutheuser** [FreeRTOS/FreeRTOS-Kernel#111]
**Describe the bug**
Uncrustify (specifically, commit 718178c68a1c863dd1a2eac7aea326a789d3bc52), broke the formatting of the portable/CCS/MSP430X/data_model.h file. The header comment syntax and the indentation are wrong.

It seems this is one of many such instances, for various assembly files.

**Target**
- Development board: MSP-EXP430FR5969
- Instruction Set Architecture: MSP430
- Toolchain and version: TI CGT msP430 20.2.0 (LTS)

**To Reproduce**
Run the FreeRTOS MSP430FR5969 launchpad demo project with at least commit 718178c68a1c863dd1a2eac7aea326a789d3bc52 of FreeRTOS-Kernel.

**Expected behavior**
The portext.asm file (this includes the erroneous data_model.h) should compile error-free.

**Additional context**
Reverting the changes introduced in 718178c68a1c863dd1a2eac7aea326a789d3bc52 fix the issue. (I.e., return to the old formatting.)

I am happy to submit a PR with the change reverted, but maybe the number of issues introduced by uncrustify indicate that a broader fix should be applied.

**Comment by alfred2g** [comment]
Hi, We are working on a fix to revert these files.
