### ISSUE TITLE
[Feature Request] Dynamic Prioritization

### ISSUE THREAD

**Issue by svenbieg** [FreeRTOS/FreeRTOS-Kernel#1134]
The problem is to define the priority on a task-level. Every task can call a critical function, so the priority has to be raised there.

My solution is a task-lock that works with a mutex. The task is marked exclusive, so interrupts are kept disabled after the task-switch until the task-lock is released.

You can take a look at the heap for example. It is used by every task and is a critical function. I'm using a task-lock there.

Best regards,

Sven Bieg

**Comment by aggarg** [comment]
Please create a post in the [FreeRTOS Forums](https://forums.freertos.org/) explaining your feature request in more detail, possibly with sequence diagrams to help us understand your request.

**Comment by svenbieg** [comment]
This time i'm sorry. You can find the detais here:

https://github.com/svenbieg/Core

I'm happy to see You again, looking forward to my Christmas holidays. My kernel took me two weeks, it's really easy with know-how.
Your vTaskSuspendAll is too expensive, You need a mutex there that can be locked exclusive. 

Good luck, to the whole FreeRTOS-team!

I'm really sorry i don't have time at the moment,

Sven Bieg

**Comment by aggarg** [comment]
Thank you for sharing your implementation. I assume you do not need anything from FreeRTOS for your implementation as your implementation does not depend on FreeRTOS.

**Comment by svenbieg** [comment]
Semaphore sounds like a german joke, "we are planing". Mutex meaning is clear mutual exclusive.

**Comment by svenbieg** [comment]
What about mutex_lock, mutex_lock_shared and mutex_lock_up?

**Comment by svenbieg** [comment]
You are right, exclusive mutual exclusion sounds funny, but it is exactly what You are missing.
If we have 100 tasks, access the heap, a high priority task is waiting, and the system timer interrupts, the high priority task has to wait for 100 tasks.
What about mutex_lock, mutex_lock_shared and mutex_lock_up?

**Comment by svenbieg** [comment]
FIFO task management

**Comment by svenbieg** [comment]
I guess this example is easier to read:

https://github.com/svenbieg/Blink

Happy Weekend!

**Comment by svenbieg** [comment]
https://github.com/svenbieg/Scheduler
