### ISSUE TITLE
[BUG] Queue allocation is broken after an update in 11.0.1. For 8-bit CPU ports.

### ISSUE THREAD

**Issue by feilipu** [FreeRTOS/FreeRTOS-Kernel#1151]
**Describe the bug**

Queues with more element bytes than `UBaseType_t` cannot be created.

**Additional context**

Originally reported by @neboskreb. https://github.com/feilipu/Arduino_FreeRTOS_Library/issues/136

**Comment by aggarg** [comment]
Thank you for reporting this.
