### ISSUE TITLE
Why not add linux simulator in FreeRTOS/Source/Portable/[compiler]/[architecture] directory?

### ISSUE THREAD

**Issue by Cherish-forever** [FreeRTOS/FreeRTOS-Kernel#116]
I think freertos can add linux simulator code to FreeRTOS/Source/Portable/[compiler]/[architecture] .

**Comment by RichardBarry** [comment]
There is a port here https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/master/portable/ThirdParty/GCC/Posix documentation will be published before the next release.
