### ISSUE TITLE
[BUG]: Fix a 'declared but never referenced' warning

### ISSUE THREAD

**Issue by rahmanih** [FreeRTOS/FreeRTOS-Kernel#1205]
IAR compiler is throwing the following warning:
```
portable/IAR/ARM_CM33_NTZ/non_secure/port.c(876) : Warning[Pe177]: function "prvGetRegionAccessPermissions" was declared but never referenced
```
the attached patch fixes it.

regards
Haithem.
[FIX_BUG_1205.TGZ](https://github.com/user-attachments/files/18091745/FIX_BUG_1205.TGZ)

**Comment by aggarg** [comment]
Thank you for reporting @rahmanih !
