### ISSUE TITLE
[Feature Request] Add titles for each column of "vTaskListTasks"

### ISSUE THREAD

**Issue by wwhheerree** [FreeRTOS/FreeRTOS-Kernel#1213]
**Is your feature request related to a problem? Please describe.**
When I use "vTaskListTasks" and print out current task report, there is no title for each column. 
For new beginners, they have to refer to FreeRTOS document for detailed decriptions of each column.
![image](https://github.com/user-attachments/assets/5c95e83d-f886-4d4f-bfec-984adb8256e8)

**Describe the solution you'd like**
I think adding a title for each column will be better for human readability.
![image](https://github.com/user-attachments/assets/8c246281-e796-4364-8f27-16b2c3dd9d66)

I have created a PR if you think this enhancement is helpful. 
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1214

**Comment by aggarg** [comment]
While this is a good suggestion, it may break existing applications using this API as it increases the required buffer size. Additionally, you can print this line in application if you want. How about adding this information in the function documentation - https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/include/task.h#L2186?

**Comment by wcai6** [comment]
OK. Can we add the below description to task.h comment? 
If yes, I will submit a PR. 

TaskName   State   Priority   HighWaterMark    TaskID
Task A            X          2               67                      2
Task B            B          1                188                   3
IDLE               R          0               67                      5

**Comment by aggarg** [comment]
Yes, that sounds good. Please raise a PR.

**Comment by wwhheerree** [comment]
PR has been submitted. 
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1215

**Comment by aggarg** [comment]
I have merged the PR #1215. Thank you for your contribution!
