### ISSUE TITLE
Stack checking method 2 improperly defined in the stack_macros.h

### ISSUE THREAD

**Issue by lcrandall** [FreeRTOS/FreeRTOS-Kernel#13]
According to the documentation [here](https://www.freertos.org/Stacks-and-stack-overflow-checking.html) setting a value of 2 to configCHECK_FOR_STACK_OVERFLOW should have the kernel check both the stack pointer position as well as the known value written to the stack when swapping tasks. As it is currently written in stack_macros.h, when configCHECK_FOR_STACK_OVERFLOW is set to 2 it only checks the known value on the stack and not the stack pointer position.  This should be changed so the stack check function does both for all values greater than 1.

**Comment by RichardBarry** [comment]
Thanks for pointing this out.  I think this is the incorrect statement "To use this method in combination with method 1 set configCHECK_FOR_STACK_OVERFLOW to 2. It is not possible to use only this method".  I will delete it.
