### ISSUE TITLE
Do you plan to add a port for ARM_CM0_MPU?

### ISSUE THREAD

**Issue by HenryGiraldo** [FreeRTOS/FreeRTOS-Kernel#155]
I am currently working with FreeRTOS and MKM34 (which is a Cortex M0+MPU) and I would like to know if you plan to add this port. Theoretically, the management of the MPU is the same as that of the other processors in the Cortex-M family.

If not, what would be the right way to add it, with a little guidance I can do it myself and make a pull request later.

**Comment by RichardBarry** [comment]
Thanks for your question - that is not on our immediate road map but the roadmap is generally driven by requests such as this.  I would be grateful if you could post future questions to the support forum where others can then pitch in if they have a similar request - https://forums.freertos.org
