### ISSUE TITLE
[BUG] 'V10.3.1' of comment remains in header part of assembly source files though FreeRTOS-Kernel V10.4.0

### ISSUE THREAD

**Issue by NoMaY-jp** [FreeRTOS/FreeRTOS-Kernel#165]
Hello,

I notice that 'V10.3.1' of comment remains in header part of assembly source files though FreeRTOS-Kernel V10.4.0 in the following Renesas RX MCUs' portable layer. Not only in case of Renesas RX MCUs but also in case of other MCUs, source files other than *.{c, h} seem to be the same.

https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5dfab0306b2f4ceb50f2200e3acf2f686ab52ab8/portable/Renesas/RX100/port_asm.src#L2
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5dfab0306b2f4ceb50f2200e3acf2f686ab52ab8/portable/Renesas/RX200/port_asm.src#L2
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5dfab0306b2f4ceb50f2200e3acf2f686ab52ab8/portable/Renesas/RX600/port_asm.src#L2
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5dfab0306b2f4ceb50f2200e3acf2f686ab52ab8/portable/Renesas/RX600v2/port_asm.src#L2
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5dfab0306b2f4ceb50f2200e3acf2f686ab52ab8/portable/Renesas/RX700v3_DPFPU/port_asm.src#L2

Best regards,
NoMaY

**Comment by RichardBarry** [comment]
Thanks.  See https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/166
