### ISSUE TITLE
[BUG] 'V10.4.0' remains in assembly source files of FreeRTOS-Kernel V10.4.1

### ISSUE THREAD

**Issue by NoMaY-jp** [FreeRTOS/FreeRTOS-Kernel#176]
Hello @RichardBarry and @dachalco,

Also this time is the same as #165, #166.

Best regards,
NoMaY

**Comment by cobusve** [comment]
Thanks for pointing this out @NoMaY-jp ! We have been automating the release process recently and the version update script is not yet as reliable as we thought!
