### ISSUE TITLE
Delaying by 0 ticks violates assert

### ISSUE THREAD

**Issue by joelfrederico** [FreeRTOS/FreeRTOS-Kernel#229]
This is undocumented and not intuitive. I would expect, like most functions, for a delay of 0 to return immediately or to be an effective context switch. I feel like one of those things would be optional. Instead, an assert is triggered. Why?

https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/47338393f1f79558f6144213409f09f81d7c4837/tasks.c#L1256

**Comment by RichardBarry** [comment]
I think this is a semantic thing.  xTaskDelayUntil() is normally used to create periodic execution, and you cannot create a task that executes every zero ticks.  Whereas passing zero into vTaskDelay() results in equivalent behaviour to calling taskYIELD().

In the future we plan to use these issues to hold our backlog, hence we prefer support requests and questions to be posted to the support forums here: https://forums.freertos.org - thanks.
