### ISSUE TITLE
Please add gitattributes file - mixed line endings make repo hard to use

### ISSUE THREAD

**Issue by tnh8** [FreeRTOS/FreeRTOS-Kernel#234]
**Describe the issue**
Having mixed line endings and not using .gitattributes is making repository harder to use. 

**Reference**
https://github.com/FreeRTOS/FreeRTOS-Kernel

**Screenshot**
`find . -not -type d -exec file "{}" ";"`

![bild](https://user-images.githubusercontent.com/50105763/102460987-0aec1880-4048-11eb-8ec8-f08734768753.png)

**Comment by dachalco** [comment]
Hi @tnh8

Good suggestion. I've Internally queued an action item to investigate this. Someone should be following up with a resolution soon. Thanks.

**Comment by dachalco** [comment]
Hi @tnh8 

Thanks again for the suggestion. I've added a `.gitattributes` to both [FreeRTOS/FreeRTOS](https://github.com/FreeRTOS/FreeRTOS/pull/490) and [FreeRTOS/FreeRTOS-Kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/245).
