### ISSUE TITLE
[Feature Request] Cosmetic issue with conditions

### ISSUE THREAD

**Issue by Hadatko** [FreeRTOS/FreeRTOS-Kernel#299]
**Is your feature request related to a problem? Please describe.**
During debugging code i noticed that you are often ussing condition (xxx != pdFALSE) and few times also (xxx != pdTRUE). Wouldn't better to replace them with oposit conditions (polite?). It is not big deal and it is up to you ;) but changing condition may improve user debug experience.

**Describe the solution you'd like**
 (xxx != pdFALSE)  =>  (xxx == pdTRUE) 
 (xxx != pdTRUE)  =>  (xxx == pdFALSE) 

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by RichardBarry** [comment]
Thanks for your feedback.  In this case I don't think this is something we will change a this time.  In general, although not always we try and do a comparison against zero (equal or not equal) as some architectures are more efficient that way - for example their first register is hard coded to zero.  Although in reality it makes little difference these days as compilers will just do the comparison the most efficient way anyway.
