### ISSUE TITLE
[BUG]:configPRE_SLEEP_PROCESSING()/configPOST_SLEEP_PROCESSING() argument passed by value.

### ISSUE THREAD

**Issue by rahmanih** [FreeRTOS/FreeRTOS-Kernel#37]
Hi,

**Describe the bug**
When the **configUSE_TICKLESS_IDLE** is enabled, the  following piece of code is executed:
<br><code>
    configPRE_SLEEP_PROCESSING( xModifiableIdleTime );
</code>
<code>
    if( xModifiableIdleTime > 0 )
</code>
<code>
    {
</code>
<code>
        __dsb( portSY_FULL_READ_WRITE );
</code>
<code>
       __wfi();
</code>
<code>
        __isb( portSY_FULL_READ_WRITE );
</code>
<code>
    }
</code>
<code>
    configPOST_SLEEP_PROCESSING( xExpectedIdleTime );
 </code>

in both  **configPRE_SLEEP_PROCESSING()** and **configPOST_SLEEP_PROCESSING()**, the arguments ,respectively ,  **_xModifiableIdleTime_** and **_xExpectedIdleTime_** , are passed by **value**, but If I understood correctly, they can be modified by the user application. Thus they should be passed by reference.

**Target**
- Development board: STM32L4 board
- Instruction Set Architecture: CM4F
- IDE and version: KEIL, IAR, GCC
- Toolchain and version: any tootchain.

regards

**Comment by RichardBarry** [comment]
Thanks for taking the time to report, however in this case this is not a bug.

configPRE_SLEEP_PROCESSING() and configPOST_SLEEP_PROCESSING() are macros, not functions, (
https://www.freertos.org/low-power-ARM-cortex-rtos.html ) - so are inlined by the preprocessor.  Therefore the parameter can be accessed directly, just like a variable, so if you want to modify it you can modify it directly.  There are some examples in the FreeRTOS download.

It may also be helpful to see the FreeRTOS style guide https://www.freertos.org/FreeRTOS-Coding-Standard-and-Style-Guide.html#NamingConventions as that describes macros as being upper case, and prefixed with the file in which they are defined.  Prefixed with 'config' means they are user modifiable and should be implemented in FreeRTOSConfig.h.
