### ISSUE TITLE
[DOC] Question about usage of doxygen tags

### ISSUE THREAD

**Issue by zikalino** [FreeRTOS/FreeRTOS-Kernel#383]
**Describe the issue**
This is more a question, rather than an issue. I am just wondering if there's any particular reason to use tags like \<pre>\</pre> around examples instead of doxygen's @code{c} @endcode ?
Same with possibility of using @note tag

**Reference**
Please attach the URL at which you are experiencing the issue.

**Screenshot**
If applicable, please attach screenshot.

**Browser**
- Browser: [e.g. Chrome]
- Version: [e.g. 80.0.3987.132]

**Comment by RichardBarry** [comment]
Hi - please post question to https://forums.freertos.org - thanks.
