### ISSUE TITLE
[BUG] Stack initialisation incorrect on dsPIC.

### ISSUE THREAD

**Issue by andrewtjs** [FreeRTOS/FreeRTOS-Kernel#404]
**Describe the bug**
When the deprecated pre-processor constant MPLAB_DSPIC_PORT is undefined, the initialisation of xInitialStack has an incorrect size, resulting in stack corruption.

**Target**
- Instruction Set Architecture: Microchip dsPIC
- IDE and version: MPLAB X v5.50
- Toolchain and version: MPLAB XC16 v1.70

**Comment by cobusve** [comment]
Fixed with PR #405
