### ISSUE TITLE
[BUG] vPortEnterCritical/vPortExitCritical bug in ARM_CM7 porting when the scheduler has not been started yet

### ISSUE THREAD

**Issue by escherstair** [FreeRTOS/FreeRTOS-Kernel#468]
Porting on ARM_CM7 implements `vPortEnterCritical()` so that it disables interrupts always, and `vPortExitCritical()` so that it enables the interrupts only if
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L420

This is necessary to handle concurrent entering/exiting critical regions from different FreeRTOS threads.

But the implementation is buggy if some function (user-defined or inside the scatterload process) calls `vPortEnterCritical()`/`vPortExitCritical()`.
This can happen, as an example if the code calls `xSemaphoreCreateMutexStatic()` before starting the scheduler (as far as I understand, this should be a perfecly legal scenario).
In this case the followin call stack is generated
`xSemaphoreCreateMutexStatic()` >> `xQueueCreateMutexStatic()` >> `xQueueGenericCreateStatic()` >> `prvInitialiseNewQueue()` >> `xQueueGenericReset()` >> `vPortEnterCritical()`/`vPortExitCritical()`

Since the scheduler has not been started yet, the variable `uxCriticalNesting` is equal to  `0xaaaaaaaa` because of its static initilization
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L142
and so this line
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L401
increments it to `0xaaaaaaab`
And as a consequence
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L418
decrements it back to `0xaaaaaaaa`
and so the comparison
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L420
is false and interrupts are not re-enabled.

One common consequence is that SysTick_Handler is not called anymore, until the task scheduler is started and `uxCriticalNesting` is properly initialized to `0`
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L364-L365

Until the scheduler is started, a function that calls CMSIS `HAL_Delay()` hangs forever, and so the instruction to enable the sceduler cannot be reached and executed. The whole application cannot work.
[Here](https://github.com/ARM-software/CMSIS-FreeRTOS/issues/55) is the detailed description of what I found.

I think that the implementation is not consistent, because I see only two different possibilities:
- if calling `vPortEnterCritical()`/`vPortExitCritical()` before the scheduler is started is supported, the interrupts must be re-enabled
- if it's not supported, a properly assert is needed instead of https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/8eb35852523b924a3a2e3a38668bacbb4b494ea5/portable/GCC/ARM_CM7/r0p1/port.c#L417

**Target**
- Development board: NUCLEO-H743ZI2
- Instruction Set Architecture: ArmV7
- IDE and version: Keil uVision V5.36.0.0
- Toolchain and version: ARM Compiler 6

**Host**
- Host OS: Windows 10
- Version: Windows 10

**To Reproduce**
- see [here](https://github.com/ARM-software/CMSIS-FreeRTOS/issues/55)

**Comment by RichardBarry** [comment]
Posted a reply here: https://github.com/ARM-software/CMSIS-FreeRTOS/issues/55 - please re-open if you still think there is a bug.
