### ISSUE TITLE
tasks.c:2067:11: warning: this condition has identical branches [-Wduplicated-branches]

### ISSUE THREAD

**Issue by pierrenoel-bouteville-act** [FreeRTOS/FreeRTOS-Kernel#476]
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/356fff8028734dc50a46972b2e315e2871b0a12e/tasks.c#L2067

We use Werror with -Wduplicated-branches own project, so this test with both case empty raise en error.

Why keep this test if both branch doe's nothing.

**Comment by jasonpcarroll** [comment]
Closing as this looks to be a PR and moved to the forum. Feel free to re-open.
