### ISSUE TITLE
[Feature Request] Cortex-M55 support

### ISSUE THREAD

**Issue by gbrtth** [FreeRTOS/FreeRTOS-Kernel#477]
**Is your feature request related to a problem? Please describe.**
Cortex-M55 is not supported yet.

**Describe the solution you'd like**
Cortex-M55 port based on Cortex-M33 port.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by RichardBarry** [comment]
The Cortex-M33 port works on the M55 too - see: https://forums.freertos.org/t/freertos-support-for-cortex-m55/14641

**Comment by RichardBarry** [comment]
Apologies - my original reply was before I noticed your PR https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/478#event-6344597561 - we will reply after taking a look at that.
