### ISSUE TITLE
[Feature Request] RISC-V stack layout

### ISSUE THREAD

**Issue by userid0x0** [FreeRTOS/FreeRTOS-Kernel#492]
**Is your feature request related to a problem? Please describe.**
In order to write an OS awareness, the debugger requires the layout of the stack in order to show the callstack of sleeping/blocked tasks. Ideally the code contains a symbol or similar where a debugger may start to unwind the stack.

**Describe the solution you'd like**
With the current status of FreeRTOS for RISC-V the `processed_source` symbol is quite useful (wished I had this for ARM CortexM).
This allows the debugger to start the unwind directly at the point where the code starts to dispatch the new task.
I want to say that removing/renaming this symbol would brick some OS awarenesses.

**Describe alternatives you've considered**
An alternative would be an struct type that matches the call stack layout.

**Comment by n9wxu** [comment]
At present there are no plans to remove the processed_source symbol. However, the nature of RISC-V as an extensible and scaleable ISA means different implementations will have different stack frames.  We are quite likely to change the stack frame as the RISC-V port matures, so we are interested in exploring “metadata” solutions that describe the stack frame for kernel aware debuggers.
