### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DanieleNardi** [FreeRTOS/FreeRTOS-Kernel#495]
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/1e0843929477c8f2e2679b70d18341ee312a5fce/portable/ThirdParty/GCC/Posix/port.c#L528

At the line linked above, the compiler signals an error because of the use of both '*' and '&' symbols when only '&' is expected. Is this an error on codebase side?

**Comment by DanieleNardi** [comment]
> I think this is fixed in the mainline already: https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/GCC/Posix/port.c#L545

Good to know, but the line in my post is the one included in the package downloadable from freeRTOS website.

**Comment by n9wxu** [comment]
The "normal" release on the website has this issue fixed.  The LTS release on the website still has the issue.  This will be corrected on the next LTS release.
