### ISSUE TITLE
[DOC] launch

### ISSUE THREAD

**Issue by Stmgme** [FreeRTOS/FreeRTOS-Kernel#527]
**Describe the issue**
Please describe the issue and expected clarification in concise language.

**Reference**
Please attach the URL at which you are experiencing the issue.

**Screenshot**
If applicable, please attach screenshot.

**Browser**
- Browser: [e.g. Chrome]
- Version: [e.g. 80.0.3987.132]

**Comment by johnrhen** [comment]
Hello Stmgme,

Are you experiencing an issue? It appears this may have been submitted in error.

**Comment by johnrhen** [comment]
We're closing this issue, please reopen if you're experiencing a problem.
