### ISSUE TITLE
[DOC][RP2040]cmake command in readme

### ISSUE THREAD

**Issue by kaidegit** [FreeRTOS/FreeRTOS-Kernel#557]
**Describe the issue**
In the readme of RP2040 port, here offered a command `import(FreeRTOS_Kernel_import.cmake)`. However, my cmake raised an error ` Unknown CMake command "import".`. I also seen the command to import freertos in `pico-example` using `include` rather than `import`. Is there a typo?

**Reference**
[the readme](https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/main/portable/ThirdParty/GCC/RP2040)

[the example](https://github.com/raspberrypi/pico-examples/blob/master/pico_w/freertos/CMakeLists.txt)

**Comment by paulbartell** [comment]
@kaidegit This is indeed a typo. Thanks for the repo.
