### ISSUE TITLE
How to know if an ISR is executing ?

### ISSUE THREAD

**Issue by edbek** [FreeRTOS/FreeRTOS-Kernel#6]
Is it possible to determine whether a method in FreeRTOS is being invoked from the context of an ISR (interrupt service request) or a task at runtime ? If this is not, will there be such a possibility in FreeRTOS in the future ? 
Thanks.

**Comment by RichardBarry** [comment]
The registers you need to read to determine if you are in an interrupt or not depends on the chip - some ports provide a macro to do this and you can do it yourself in cases where the macro doesn't exist.  Which port (chip and compiler) are you using?

**Comment by edbek** [comment]
I use chip i.MX RT1064 and design environment MCUXpresso IDE.
Thank you.

**Comment by edbek** [comment]
Is it possible to make a list of macros to determine the location inside interrupts for all popular processors?

**Comment by RichardBarry** [comment]
> I use chip i.MX RT1064 and design environment MCUXpresso IDE.
> Thank you.

In which case you can use [xPortIsInsideInterrupt()](https://sourceforge.net/p/freertos/code/HEAD/tree/tags/V10.2.1/FreeRTOS/Source/portable/GCC/ARM_CM4F/portmacro.h#l169).

**Comment by RichardBarry** [comment]
In future please post support requests to https://forums.freertos.org - thanks.
