### ISSUE TITLE
[BUG] Build With CMake and GCC as static library

### ISSUE THREAD

**Issue by 0x7a657573** [FreeRTOS/FreeRTOS-Kernel#646]
**Describe the bug**
I tried to add FreeRTOS on my CMake Project but in compile time I get some error like this:

[build] ../system/FreeRTOS/portable/GCC/ARM_CM3/portmacro.h:135:51: error: unknown type name 'inline'
[build]          __attribute__( ( always_inline ) ) static inline uint8_t ucPortCountLeadingZeros( uint32_t ulBitmap )

I think this error happen because in the FreeRTOS, CMakelists.txt at line 296 say to compiler use C90 standard.
`set_property(TARGET freertos_kernel PROPERTY C_STANDARD 90)
`
when I change this line to use GNU99 standard, error is gone !

**Target**
- Development board: [STM32F103CBT6]
- Instruction Set Architecture: [ARM Cortex-m3]
- IDE and version: [vscode]
- Toolchain and version: [GCC arm-none-eabi-8.3.1]

**Host**
- Host OS: [Linux]
- Version: [Debian 11.6]

**Comment by RichardBarry** [comment]
Grateful if you can create a support thread on this at https://forums.freertos.org until we determine the route cause as the kernel should build with C90, and GCC is happy with "inline".  Thanks.

**Comment by 0x7a657573** [comment]
I posted my Issue to [forums.freertos.org](https://forums.freertos.org/t/freertos-gcc-cmake/16984)
