### ISSUE TITLE
[BUG]warnings when LARGE DATA MODEL used on MSP430 CCS port

### ISSUE THREAD

**Issue by dimitrovand** [FreeRTOS/FreeRTOS-Kernel#671]
**Describe the bug**
Warnings in **portext.asm** from **portSAVE_CONTEXT** and **portRESTORE_CONTEXT** dew to usage of **mov.w** in large data model. Using **mov_x** resolves all warnings.

**Target**
- Development board: MSP-EXP430FR5994
- IDE and version: Code Composer Studio 12.1.0.00007
- Toolchain and version: Default for the IDE version

**Host**
- Host OS: Windows
- Version: 11

**To Reproduce**
- Use any project containing the FreeRTOS port
- In linker script select data and code to be moved to higher FRAM (FRAM2)
- In project settings select **Properties->Build->MSP430 Compiler->Processor Options** and select **large data/code models + --near_data = none**
- Add **__LARGE_DATA_MODEL__** in **Properties->Build->MSP430 Compiler->Predefined Symbols**

**Expected behavior**
No warnings

**Screenshots**
![freertos](https://user-images.githubusercontent.com/42586041/236506591-c78ba20a-1cec-4735-8af6-d502424b581b.png)

**Comment by moninom1** [comment]
Hi @dimitrovand 

Thank you for reporting the issue!
We are looking further into this issue. Will update in a while. Thank you for your patience!

**Comment by aggarg** [comment]
Fixed in this PR - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/676
