### ISSUE TITLE
[BUG] Raspberry pi Pico FreeRTOS SMP freezes after some time

### ISSUE THREAD

**Issue by RazRabino** [FreeRTOS/FreeRTOS-Kernel#672]
**Describe the bug**
I'm using FreeRTOS SMP kernel on my raspberry pi pico, the project is a flight controller for an RC plane,
I created a task (my only task currently running) that performs IMU reading using mutex semaphore.
in the past (on the FreeRTOS non-SMP version) the code worked (without semaphores) but now everything freezes
after some time, with heap3 and fewer prints than what I use now, the Pico froze after 5 minutes.
now with heap4 and more detailed prints of the memory, it freeze after half a minute.
In another test (in that test I read data from the imu sensor every 1000ms and not 5ms) the pico froze after 15mins.
with the non-SMP version, the same IMU read ran for more than 20 minutes (after 20 minutes I stopped it 
but it keep running).

**Target**
- Development board: Raspberry pi pico w
- Instruction Set Architecture: Dual-core Arm Cortex M0+
- IDE and version: Visual Studio code
- Toolchain and version: Pico SDK - 1.4.0

**Host**
- Host OS: Windows 11
- Version: 10.0.22621 Build 22621

**To Reproduce**
- Use project  - the project didn't upload to GitHub yet.
- Run on - let the Pico run for some time and see it freeze.

**Expected behavior**
The Pico board will run without freeze

**Additional context**
console prints of the Pico with heap4 and detailed memory info - https://pastebin.com/nxXi5GH0?fbclid=IwAR1VESb4gHGm-zHwg3VihcX5Z98fTyajWCxL24_81rVDCUL6Zti01nMvfcU

task function - https://pastebin.com/ewFKrKjG?fbclid=IwAR3vPqGv9Gvf_tAEl3_lYpec2Y0QVz5w3q4hYKlwe_r2uPUdp-Awu_epIJg

old heap3 with stack prints only - https://pastebin.com/ZVaCHkMn?fbclid=IwAR3nB8YBAySrl6ok5v72DrjT19_TQa9d-t7_IMSBQ3-7_ivVLQLVa9i3D4Y

console prints of the Pico with heap4 and detailed memory info without any semaphore or vTaskPreemptionEnable calling - https://pastebin.com/PwiF99qt

IMU function - https://pastebin.com/TC52abF6?fbclid=IwAR0iU4ykUMnkgeJoQ9nUTD6vxtmnrvmuOTBYG_lTX5Dh7yiwHcLaEmfrzVk

Main - task creation:
----------------------------------------------------------------------------------
    TaskHandle_t xImuHandle;
    UBaseType_t uxImuCoreAffinityMask = ( 1 << 1);
    xTaskCreate(imu_reader, "IMU_Task", 256, &(sdh), 3, &(xImuHandle));
    vTaskCoreAffinitySet(xImuHandle, uxImuCoreAffinityMask);

    std::cout << "vTaskStartScheduler started!" << std::endl;

    vTaskStartScheduler();
----------------------------------------------------------------------------------

**Comment by RichardBarry** [comment]
I would be grateful if you can open a support request on https://forums.freertos.org (you can use your github account to post).  If the support thread concludes there is indeed a bug then we can reopen this ticket.
