### ISSUE TITLE
Errno 11 in projdefs.h is used twice

### ISSUE THREAD

**Issue by dervomsee** [FreeRTOS/FreeRTOS-Kernel#684]
Errno 11 is used twice: https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/953c1ee6cbf460092826bab772e4119c6d9e51e8/include/projdefs.h#L86

See also https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/888

**Comment by RichardBarry** [comment]
Thanks for reporting, but this is intentional and as expected.  Search for EAGAIN on https://man7.org/linux/man-pages/man3/errno.3.html.
