### ISSUE TITLE
[BUG] Missing portPOINTER_SIZE_TYPE  definition for ATmega port

### ISSUE THREAD

**Issue by jputcu** [FreeRTOS/FreeRTOS-Kernel#697]
The Atmega port: `portable/ThirdParty/GCC/ATmega/portmacro.h` needs the following:
~~~~
#define portPOINTER_SIZE_TYPE uint16_t
~~~~

**Comment by kstribrnAmzn** [comment]
Thank you for raising this issue! While I'm happy to make the change on your behalf, would you like to make the change? In doing so you'll get to contribute a fix for a bug you've identified.

**Comment by kstribrnAmzn** [comment]
The ports _should be extremely similar_. The key difference is how these ports got created. The ATMega323 port was most likely created by the FreeRTOS team. The more general, third party ATMega port was actually created in [this PR](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/48) by a contributing community member.

As mentioned in that PR, there are several ATMega chips which aren't supported. Digging through the commits to the port files, it looks like these chips are still not supported as no further work to them has been done.

If additional ports are needed, we'd love for you to either submit a PR contributing them or create a feature request for whatever ports you need. We use feature requests to understand user needs.
