### ISSUE TITLE
[BUG] Windows 64-bit MingW error in xQueueGenericCreate port due to comparison of different types

### ISSUE THREAD

**Issue by jputcu** [FreeRTOS/FreeRTOS-Kernel#710]
Using the current `master` and the `FreeRTOS\portable\MSVC-MingW` port on Windows 64-bit machine I get the following error:
~~~~
FreeRTOS/queue.c: In function 'xQueueGenericCreate':
FreeRTOS/queue.c:489:48: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  489 |             ( ( SIZE_MAX - sizeof( Queue_t ) ) >= ( uxQueueLength * uxItemSize ) ) )
      |                                                ^~
cc1.exe: all warnings being treated as errors
~~~~

The right hand side: `UBaseType_t` is an `unsigned long`(32-bit). The left side is `uint64_t`(64-bit). Sizes don't match.

**Comment by aggarg** [comment]
Are you choosing `x64` as the platform in your VS project? Can you try changing it to WIN32?


<img width="482" alt="Untitled" src="https://github.com/FreeRTOS/FreeRTOS-Kernel/assets/33462878/8de298e1-af18-4a7c-92fe-d00950f75c75">

**Comment by jputcu** [comment]
I'm using `msys2/ucrt64` on the command line with `gcc`. I think we need to cast the left side to `UBaseType_t` or make that type a `size_t` or `unsigned long long` in the port, but I don't know what that would impact.

**Comment by aggarg** [comment]
Can you try changing [these lines](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/MSVC-MingW/portmacro.h#L49-L50) to the following - 

```
#if defined( __x86_64__) || defined( _M_X64 )
    typedef long long BaseType_t;
    typedef unsigned long long UBaseType_t;
#else
    typedef long BaseType_t;
    typedef unsigned long UBaseType_t;
#endif
```

**Comment by jputcu** [comment]
I currently don't have access to my work (Windows) PC, but I feels we are actually just recreating `size_t`.

**Comment by RichardBarry** [comment]
Sorry - not in a position to look at the actual code or reproduce the error right now, but concur other places in the code use size_t to switch between 32 and 64-bit architectures.

**Comment by aggarg** [comment]
@jputcu Were you able to try out my suggestion?

**Comment by jputcu** [comment]
@aggarg I just tried it and the compiler warning is gone.

**Comment by aggarg** [comment]
Thanks for confirming. I have created the following PR to fix this - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/715
