### ISSUE TITLE
Allow Top/End of stack to be returned in vTaskGetInfo whenever available. 

### ISSUE THREAD

**Issue by vinceburns** [FreeRTOS/FreeRTOS-Kernel#729]
**Is your feature request related to a problem? Please describe.**
https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/c4f9e27c28c018c85b9d23e5ac7470ada508bdb8
This was a neat feature to be added. However, the implementation forces you to use positive stack growth in order to get that:
```
        #if ( ( portSTACK_GROWTH > 0 ) && ( configRECORD_STACK_HIGH_ADDRESS == 1 ) )
            pxTaskStatus->pxTopOfStack = pxTCB->pxTopOfStack;
            pxTaskStatus->pxEndOfStack = pxTCB->pxEndOfStack;
        #endif
```
Because the pxEndOfStack Pointer is stored in the tcb anytime you have either of those options, I don't see a need for that.
```
    #if ( ( portSTACK_GROWTH > 0 ) || ( configRECORD_STACK_HIGH_ADDRESS == 1 ) )
        StackType_t * pxEndOfStack; /**< Points to the highest valid address for the stack. */
    #endif
```

**Describe the solution you'd like**
I think that data can be returned whenever it is available with 2 one-line changes. In the 
```
        #if ( ( portSTACK_GROWTH > 0 ) || ( configRECORD_STACK_HIGH_ADDRESS == 1 ) )
            pxTaskStatus->pxTopOfStack = pxTCB->pxTopOfStack;
            pxTaskStatus->pxEndOfStack = pxTCB->pxEndOfStack;
        #endif
 ```
and 
```
    #if ( ( portSTACK_GROWTH > 0 ) || ( configRECORD_STACK_HIGH_ADDRESS == 1 ) )
        StackType_t * pxTopOfStack;               /* Points to the top address of the task's stack area. */
        StackType_t * pxEndOfStack;               /* Points to the end address of the task's stack area. */
    #endif
 ```

**Describe alternatives you've considered**
There really isn't an alternative. I've hacked in a way to get that data in my local copy of my library to get what I need. 

**How many devices will this feature impact?**
100000+

**What are your project timelines?**
This would be used for remote diagnostics. There isn't an immediate need, but it would be nice if the next release included this. 

**Additional context**
The desire for this comes from wanting to create a core dump when a fault occurs. With the EndofStack, a stack dump can be generated and stored prior to resetting. Then after a reset that dump can be sent to a remote server. I have written a Python script that takes in a disassembly file and the stack dump to recreate a call stack for remote diagnostic of what caused the fault. 

If you have the same (or similar) feature request, please upvote this issue with thumbs up 👍
and use the comments section to provide answers to the questions above.

**Comment by ActoryOu** [comment]
Thanks for your contribution!
PR has been merged thus I'm closing this issue.
