### ISSUE TITLE
Support ARMV8M without trust-zone

### ISSUE THREAD

**Issue by cyliangtw** [FreeRTOS/FreeRTOS-Kernel#74]
In current `/portable/ARMv8M`, it could support V8M with trust-zone for secure or non-secure build.
However, some chip of V8M cpu core is not including trust-zone feature and current `/portable/ARMv8M` can't support this kind chip.
Is there any plan to add-on V8M without trust-zone in  `/portable` ?

**Comment by RichardBarry** [comment]
Grateful if you can post your question to https://forums.freertos.org where we will be happy to provide an answer.
