### ISSUE TITLE
[Feature Request] Support configurable RISC-V chip extension

### ISSUE THREAD

**Issue by JoeBenczarski** [FreeRTOS/FreeRTOS-Kernel#772]
The problem is that not all RISC-V chip extensions are supported for all compilers.

The solution would be to add a FREERTOS_RISC_EXTENSION option to the CMake project similar to how FREERTOS_PORT is used. The CMake project would issue an error and provide valid options if the user chooses a RISC_V port but does not specify a chip extension folder name.

**Comment by chinglee-iot** [comment]
@JoeBenczarski 
The PR is merged. Thank you for your contribution.
