### ISSUE TITLE
[BUG] xStreamBufferCreateStatic() fails when xBufferSizeBytes is 1.

### ISSUE THREAD

**Issue by anolivetree** [FreeRTOS/FreeRTOS-Kernel#792]
**Describe the bug**
xStreamBufferCreateStatic() fails when xBufferSizeBytes is 1.

**To Reproduce**
- call xStreamBufferCreateStatic() with xBufferSizeBytes 1

**Expected behavior**
- creates stream buffer successfully.

**Additional context**
xStreamBufferGenericCreateStatic do following check even when xIsMessageBuffer is pdFALSE.

> configASSERT( xBufferSizeBytes > sbBYTES_TO_STORE_MESSAGE_LENGTH );

It seems the check should be executed only when xIsMessageBuffer is pdTRUE, just like xStreamBufferGenericCreate() does.

**Comment by kar-rahul-aws** [comment]
Hi @anolivetree 
Thank you for reporting this issue. I have created a patch for the fix, and it has been merged to the mainline. Please let us know if this fixes the issue you were observing.
Thanks.

**Comment by kar-rahul-aws** [comment]
Sure, thank you for the update.
Closing the issue.
