### ISSUE TITLE
[Feature Request] <Tasks on the prvCheckTasksWaitingTermination list should not be suspended>

### ISSUE THREAD

**Issue by lemonking77** [FreeRTOS/FreeRTOS-Kernel#892]
Whether vTaskSuspend should determine whether the task to be suspended is on prvCheckTasksWaitingTermination. If the task to be suspended is on prvCheckTasksWaitingTermination, it should not be suspended, but should be released as early as possible in the idle task. This is my question, I hope it can be answered. Thank you so much.

**Comment by RichardBarry** [comment]
Hi - thanks for your question.  We prefer to discuss these things in the support forums first.  Doing so helps users navigate the github tickets to find open bugs and feature requests, etc. without the noise of support conversations in the mix.  Forum conversations that confirm bugs result in tickets being opened here.  So please repost your question to https://forums.freertos.org - you can use your github account to sign in.
