### ISSUE TITLE
FreeRTOS-Kernel V11 - SMP

### ISSUE THREAD

**Issue by amazonKamath** [FreeRTOS/FreeRTOS-Kernel#904]
Symmetric Multiprocessing (SMP) support in the FreeRTOS Kernel enables one instance of the FreeRTOS kernel to schedule tasks across multiple identical processor cores. Currently, SMP support exists in a separate branch. This work item involves releasing the FreeRTOS SMP support as Generally Available and have a common codebase for single core and SMP.

**Comment by sirnish** [comment]
Please read more [here](https://freertos.org/2023/12/introducing-freertos-kernel-version-11-0-0-a-major-release-with-symmetric-multiprocessing-smp-support.html)

**Comment by sirnish** [comment]
Please see more [here](https://freertos.org/2023/12/introducing-freertos-kernel-version-11-0-0-a-major-release-with-symmetric-multiprocessing-smp-support.html)

**Comment by aggarg** [comment]
Thank you for pointing. I have updated the link.
