### ISSUE TITLE
SESIP Level 3 Certification

### ISSUE THREAD

**Issue by amazonKamath** [FreeRTOS/FreeRTOS-Kernel#907]
This is an effort to get Security Evaluation Standard for IoT Platforms (SESIP) Assurance Level 3 certification working with a third party lab

**Comment by AniruddhaKanhere** [comment]
FreeRTOS has received the SESIP level 3 certification which can be found on the certifier TrustCB website [here](https://www.trustcb.com/iot/sesip/sesip-certificates/).

More details can be found in this blog post: https://freertos.org/Community/Blogs/2024/freertos-is-now-sesip-level3-certified
