### ISSUE TITLE
[BUG] - uncrustify breaks formatting for inline assembly in ATmega port

### ISSUE THREAD

**Issue by feilipu** [FreeRTOS/FreeRTOS-Kernel#91]
**Describe the bug**
Uncrustify breaks formatting for inline assembly code in port.c and portmacro.h. This makes the code unreadable.

**Target**
ThirdParty/GCC/ATmega

**Expected behavior**
Human legible code.

** Current situation**
![port c](https://user-images.githubusercontent.com/3955592/87748079-4f288200-c838-11ea-8cc6-0cfd97122bd5.png)
![portmacro h](https://user-images.githubusercontent.com/3955592/87748085-5059af00-c838-11ea-89b6-8bfe5f488e17.png)

**Comment by lundinc2** [comment]
Hello @feilipu,

Thank you for submitting this report. It seems uncrustify has caused several issues. We will investigate and report back with a fix.

**Comment by alfred2g** [comment]
Code is now looking readable to some people at least :) 
closing the issue
