### ISSUE TITLE
smp for cortex-m7

### ISSUE THREAD

**Issue by snikeguo** [FreeRTOS/FreeRTOS-Kernel#929]
rt.
I'm using s32k324 which contains two coretex-m7 CPU ip cores, how do I port FreeRTOS SMP to coretex-m7?

**Comment by kar-rahul-aws** [comment]
Hi @snikeguo 
Thanks for your question. Our preference is to post questions to https://forums.freertos.org/ to keep them all in the same place, and leave the github issues for bugs, roadmap items, etc.
You can refer to this [post ](https://forums.freertos.org/t/smp-porting-checklist-a53-4-as-reference/14499)on forums, which can act as a porting guide for SMP on Cortex M7.
