### ISSUE TITLE
MPU V2 for CM3 & CM4

### ISSUE THREAD

**Issue by rahmanih** [FreeRTOS/FreeRTOS-Kernel#930]
Hi,

Is there any plan to deploy the MPU wrapper V2 for CM3 & CM4 ports.

regards
Haithem.

**Comment by RichardBarry** [comment]
Hi - thanks for your question.  Our preference is to post questions to https://forums.freertos.org to keep them all in the same place, and leave the github issues for bugs, roadmap items, etc.  If you would like to post your question again on the forum I will be happy to point you in the right direction.  You can post using your github login.
