### ISSUE TITLE
Could provide a .uncrustify.cfg file in root directory

### ISSUE THREAD

**Issue by YuguoWH** [FreeRTOS/FreeRTOS-Kernel#98]
late commits of uncrustify has made some code unreable, and new code submit could also bring code style problems. Therefore I would suggest puting a .uncrustify.cfg in root directory. So pull requests could align to a specify code style before they are merged, and also presenting a chance to find bugs ahead.

**Comment by lundinc2** [comment]
Hello @YuguoWH,

I am in the process of determining a proper locating for the uncrustify associated with the kernel.

Thanks

**Comment by lundinc2** [comment]
Hello @YuguoWH,

I have updated the Readme in this repository to specify where the uncrustify config can be found. We decided to put it in FreeRTOS/FreeRTOS, under the tools directory, in to keep this repository small. Thank you for bringing this to our attention and please re-open this issue for further help.
