### ISSUE TITLE
FreeRTOS.h configSTACK_DEPTH_TYPE inconsistent with default type

### ISSUE THREAD

**Issue by feilipu** [FreeRTOS/FreeRTOS-Kernel#986]
**Description**
In #942 the [default configuration value was inadvertently left set as __`uint16_t`__](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/include/FreeRTOS.h#L2800-L2805) in `FreeRTOS.h`. Later updates to the merged PR omitted to update the configuration default to `StackType_t`.

It should be updated to `StackType_t`, to match the rest of the already merged PR #942. 

**Targets**
All targets use `FreeRTOS.h`, where the default is incorrect.

**Additional context**
Some targets need to use the added default definition in `portable.h` from #942 to build, as they don't include `FreeRTOS.h` before using the definition. I think that this is probably bad, and is probably bugged too.

The duplicate default in `portable.h` should be removed, when the ports are repaired.

**Comment by kar-rahul-aws** [comment]
Hi @feilipu 
Thanks for pointing the issue. We have merged the PR #987 with the necessary changes . We will look into the port issues you mentioned and address it in a later PR, if required.
