### ISSUE TITLE
[Feature Request] Default Affinity Set

### ISSUE THREAD

**Issue by go2sh** [FreeRTOS/FreeRTOS-Kernel#993]
**Is your feature request related to a problem? Please describe.**
We created a freeRTOS SMP port for the Infineon TC3x and TC4x family, but the system design is not really symmetrical. Especially the Task context ist bound to the CPU executing the task. This makes switching tasks between different CPUs nearly impossible. But the SMP design still makes some sense to distribute work across cores more easily. For example in conjunction with FreeRTOS-Plus-TCP to distribute sockets across cores.

**Describe the solution you'd like**
Create a new config flag to allow setting a default affinity for a task, where no affinity set is provided during task creation. This is especially useful for legacy code. This could either be a fixed value or the current core, who creates the task.

**Describe alternatives you've considered**
Non

**How many devices will this feature impact?**
All TC3x and TC4x devices with SMP enabled.

**What are your project timelines?**
A patch is already prepared internally.

**Comment by go2sh** [comment]
Would you accept a PR for this?

**Comment by rawalexe** [comment]
Hello thank you so much for reporting about this problem, we can definitely consider accepting the PR, Please feel free to go ahead and create your PR, the team can have look at it and share more details on it.
