### ISSUE TITLE
Add support to cortex A7

### ISSUE THREAD

**Issue by rahmanih** [FreeRTOS/FreeRTOS-Kernel#997]
Hi,

We noticed that only the A9 is supported  in the Cortex A family.
is this port compatible with cortex A7?
otherwise is there any plan to support the Cortex A7 CPU?

regards
haithem.

**Comment by paulbartell** [comment]
@rahmanih Due to the shared ARMv7-A architecture, the Cortex-A9 port should also work for a Cortex-A7.

**Comment by RichardBarry** [comment]
I believe it has been used with A7 several times before.

**Comment by rahmanih** [comment]
thanks @RichardBarry @paulbartell  for the prompt answer.

regards
Haithem.
